// export const UPDATE_DATA_MESSAGE_FORM = "UPDATE_DATA_MESSAGE_FORM";
// export const DELETE_TEXT_MESSAGE_FORM = "DELETE_TEXT_MESSAGE_FORM";

// export const UPDATEDELIVER = "UPDATE_DELIVERY";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const SEND_TEXT = "SEND_TEXT";
export const SEND_IMAGE = "SEND_IMAGE";
export const SEND_FILE = "SEND_FILE";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const REWRITE_TEXT = "REWRITE_TEXT";
export const TOGGLE_EXTRAS = "TOGGLE_EXTRAS";
